sudo: false
language: node_js
node_js:
  - "iojs"
  - "0.10"
  - "0.11"
  - "0.12"
matrix:
  allow_failures:
    - node_js: "0.10"
script: "npm run-script test-travis"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"